[package]
name = "silkproto"
version = "0.0.1"
keywords = ["silk"]
edition = "2018"
build = "build.rs"

[lib]
name = "silkproto"
path = "src/lib.rs"

[features]
default = ["protobuf-codec"]
protobuf-codec = ["protobuf-build/grpcio-protobuf-codec",  "grpcio/protobuf-codec"]
prost-codec = ["prost", "prost-derive", "bytes", "lazy_static", "protobuf-build/grpcio-prost-codec",  "grpcio/prost-codec"]

[dependencies]
protobuf = "=2.8.0"
prost = { version = "0.5", optional = true }
prost-derive = { version = "0.5", optional = true }
bytes = { version = "0.4", optional = true }
futures = "0.1"
grpcio = { version = "0.5.0-alpha.3", default-features = false, features = ["secure"] }
lazy_static = { version = "1.3", optional = true }

[build-dependencies]
protobuf-build = { version = "0.10", default-features = false }

[replace]
"protobuf-codegen:2.8.0" = { git = "https://github.com/pingcap/rust-protobuf", rev="b67d432c1b74350b38a5d96ddf885ac6c3ff46f5" }
"protobuf:2.8.0" = { git = "https://github.com/pingcap/rust-protobuf", rev="b67d432c1b74350b38a5d96ddf885ac6c3ff46f5" }
"protobuf-build:0.10.0" = { git = "https://github.com/tikv/protobuf-build", rev="1fe5d77689d9691b7917215f3a1d32968115cc02" }
